# Not using to test compilation of go component of project because it requires
# xcodebuild which is not available in the ubuntu environment travis-ci
# provides.
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.1.3
  - rbx-2
gemfile: rubygem/Gemfile
script: make rubygem/lib/zeus/version.rb && cd rubygem && bundle install --without development && bundle exec rspec spec

